/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as AboutCommunityRouteImport } from './routes/about.community'
import { Route as AboutFacilitiesRouteImport } from './routes/about.facilities'
import { Route as AboutHistoryRouteImport } from './routes/about.history'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as PeopleSlugRouteImport } from './routes/people.$slug'
import { Route as PracticeAreasIndexRouteImport } from './routes/practice-areas.index'
import { Route as PracticeAreasSlugRouteImport } from './routes/practice-areas.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutCommunityRoute = AboutCommunityRouteImport.update({
  id: '/about/community',
  path: '/about/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutFacilitiesRoute = AboutFacilitiesRouteImport.update({
  id: '/about/facilities',
  path: '/about/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutHistoryRoute = AboutHistoryRouteImport.update({
  id: '/about/history',
  path: '/about/history',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleSlugRoute = PeopleSlugRouteImport.update({
  id: '/people/$slug',
  path: '/people/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeAreasIndexRoute = PracticeAreasIndexRouteImport.update({
  id: '/practice-areas/',
  path: '/practice-areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeAreasSlugRoute = PracticeAreasSlugRouteImport.update({
  id: '/practice-areas/$slug',
  path: '/practice-areas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/about/community': typeof AboutCommunityRoute
  '/about/facilities': typeof AboutFacilitiesRoute
  '/about/history': typeof AboutHistoryRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/practice-areas/$slug': typeof PracticeAreasSlugRoute
  '/about/': typeof AboutIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/practice-areas/': typeof PracticeAreasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/about/community': typeof AboutCommunityRoute
  '/about/facilities': typeof AboutFacilitiesRoute
  '/about/history': typeof AboutHistoryRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/practice-areas/$slug': typeof PracticeAreasSlugRoute
  '/about': typeof AboutIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/people': typeof PeopleIndexRoute
  '/practice-areas': typeof PracticeAreasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/about/community': typeof AboutCommunityRoute
  '/about/facilities': typeof AboutFacilitiesRoute
  '/about/history': typeof AboutHistoryRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/practice-areas/$slug': typeof PracticeAreasSlugRoute
  '/about/': typeof AboutIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/practice-areas/': typeof PracticeAreasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/contact'
    | '/privacy'
    | '/about/community'
    | '/about/facilities'
    | '/about/history'
    | '/insights/$slug'
    | '/people/$slug'
    | '/practice-areas/$slug'
    | '/about/'
    | '/insights/'
    | '/people/'
    | '/practice-areas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/contact'
    | '/privacy'
    | '/about/community'
    | '/about/facilities'
    | '/about/history'
    | '/insights/$slug'
    | '/people/$slug'
    | '/practice-areas/$slug'
    | '/about'
    | '/insights'
    | '/people'
    | '/practice-areas'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/contact'
    | '/privacy'
    | '/about/community'
    | '/about/facilities'
    | '/about/history'
    | '/insights/$slug'
    | '/people/$slug'
    | '/practice-areas/$slug'
    | '/about/'
    | '/insights/'
    | '/people/'
    | '/practice-areas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  AboutCommunityRoute: typeof AboutCommunityRoute
  AboutFacilitiesRoute: typeof AboutFacilitiesRoute
  AboutHistoryRoute: typeof AboutHistoryRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  PeopleSlugRoute: typeof PeopleSlugRoute
  PracticeAreasSlugRoute: typeof PracticeAreasSlugRoute
  AboutIndexRoute: typeof AboutIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  PracticeAreasIndexRoute: typeof PracticeAreasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/community': {
      id: '/about/community'
      path: '/about/community'
      fullPath: '/about/community'
      preLoaderRoute: typeof AboutCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/facilities': {
      id: '/about/facilities'
      path: '/about/facilities'
      fullPath: '/about/facilities'
      preLoaderRoute: typeof AboutFacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/history': {
      id: '/about/history'
      path: '/about/history'
      fullPath: '/about/history'
      preLoaderRoute: typeof AboutHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$slug': {
      id: '/people/$slug'
      path: '/people/$slug'
      fullPath: '/people/$slug'
      preLoaderRoute: typeof PeopleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-areas/': {
      id: '/practice-areas/'
      path: '/practice-areas'
      fullPath: '/practice-areas/'
      preLoaderRoute: typeof PracticeAreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-areas/$slug': {
      id: '/practice-areas/$slug'
      path: '/practice-areas/$slug'
      fullPath: '/practice-areas/$slug'
      preLoaderRoute: typeof PracticeAreasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  AboutCommunityRoute: AboutCommunityRoute,
  AboutFacilitiesRoute: AboutFacilitiesRoute,
  AboutHistoryRoute: AboutHistoryRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  PeopleSlugRoute: PeopleSlugRoute,
  PracticeAreasSlugRoute: PracticeAreasSlugRoute,
  AboutIndexRoute: AboutIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  PracticeAreasIndexRoute: PracticeAreasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
