/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ShellRouteImport } from './routes/shell'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as AboutCommunityRouteImport } from './routes/about.community'
import { Route as AboutFacilitiesRouteImport } from './routes/about.facilities'
import { Route as AboutHistoryRouteImport } from './routes/about.history'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsPublicationsRouteImport } from './routes/insights.publications'
import { Route as InsightsTalksRouteImport } from './routes/insights.talks'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as PeopleSlugRouteImport } from './routes/people.$slug'
import { Route as PracticeAreasIndexRouteImport } from './routes/practice-areas.index'
import { Route as PracticeAreasSlugRouteImport } from './routes/practice-areas.$slug'
import { Route as InsightsNewsIndexRouteImport } from './routes/insights.news.index'
import { Route as InsightsNewsSlugRouteImport } from './routes/insights.news.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/shell',
  path: '/shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutCommunityRoute = AboutCommunityRouteImport.update({
  id: '/about/community',
  path: '/about/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutFacilitiesRoute = AboutFacilitiesRouteImport.update({
  id: '/about/facilities',
  path: '/about/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutHistoryRoute = AboutHistoryRouteImport.update({
  id: '/about/history',
  path: '/about/history',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsPublicationsRoute = InsightsPublicationsRouteImport.update({
  id: '/insights/publications',
  path: '/insights/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsTalksRoute = InsightsTalksRouteImport.update({
  id: '/insights/talks',
  path: '/insights/talks',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleSlugRoute = PeopleSlugRouteImport.update({
  id: '/people/$slug',
  path: '/people/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeAreasIndexRoute = PracticeAreasIndexRouteImport.update({
  id: '/practice-areas/',
  path: '/practice-areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeAreasSlugRoute = PracticeAreasSlugRouteImport.update({
  id: '/practice-areas/$slug',
  path: '/practice-areas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsNewsIndexRoute = InsightsNewsIndexRouteImport.update({
  id: '/insights/news/',
  path: '/insights/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsNewsSlugRoute = InsightsNewsSlugRouteImport.update({
  id: '/insights/news/$slug',
  path: '/insights/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/shell': typeof ShellRoute
  '/about/community': typeof AboutCommunityRoute
  '/about/facilities': typeof AboutFacilitiesRoute
  '/about/history': typeof AboutHistoryRoute
  '/insights/publications': typeof InsightsPublicationsRoute
  '/insights/talks': typeof InsightsTalksRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/practice-areas/$slug': typeof PracticeAreasSlugRoute
  '/about/': typeof AboutIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/practice-areas/': typeof PracticeAreasIndexRoute
  '/insights/news/$slug': typeof InsightsNewsSlugRoute
  '/insights/news/': typeof InsightsNewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/shell': typeof ShellRoute
  '/about/community': typeof AboutCommunityRoute
  '/about/facilities': typeof AboutFacilitiesRoute
  '/about/history': typeof AboutHistoryRoute
  '/insights/publications': typeof InsightsPublicationsRoute
  '/insights/talks': typeof InsightsTalksRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/practice-areas/$slug': typeof PracticeAreasSlugRoute
  '/about': typeof AboutIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/people': typeof PeopleIndexRoute
  '/practice-areas': typeof PracticeAreasIndexRoute
  '/insights/news/$slug': typeof InsightsNewsSlugRoute
  '/insights/news': typeof InsightsNewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/shell': typeof ShellRoute
  '/about/community': typeof AboutCommunityRoute
  '/about/facilities': typeof AboutFacilitiesRoute
  '/about/history': typeof AboutHistoryRoute
  '/insights/publications': typeof InsightsPublicationsRoute
  '/insights/talks': typeof InsightsTalksRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/practice-areas/$slug': typeof PracticeAreasSlugRoute
  '/about/': typeof AboutIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/practice-areas/': typeof PracticeAreasIndexRoute
  '/insights/news/$slug': typeof InsightsNewsSlugRoute
  '/insights/news/': typeof InsightsNewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/privacy'
    | '/shell'
    | '/about/community'
    | '/about/facilities'
    | '/about/history'
    | '/insights/publications'
    | '/insights/talks'
    | '/people/$slug'
    | '/practice-areas/$slug'
    | '/about/'
    | '/insights/'
    | '/people/'
    | '/practice-areas/'
    | '/insights/news/$slug'
    | '/insights/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/privacy'
    | '/shell'
    | '/about/community'
    | '/about/facilities'
    | '/about/history'
    | '/insights/publications'
    | '/insights/talks'
    | '/people/$slug'
    | '/practice-areas/$slug'
    | '/about'
    | '/insights'
    | '/people'
    | '/practice-areas'
    | '/insights/news/$slug'
    | '/insights/news'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/privacy'
    | '/shell'
    | '/about/community'
    | '/about/facilities'
    | '/about/history'
    | '/insights/publications'
    | '/insights/talks'
    | '/people/$slug'
    | '/practice-areas/$slug'
    | '/about/'
    | '/insights/'
    | '/people/'
    | '/practice-areas/'
    | '/insights/news/$slug'
    | '/insights/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ShellRoute: typeof ShellRoute
  AboutCommunityRoute: typeof AboutCommunityRoute
  AboutFacilitiesRoute: typeof AboutFacilitiesRoute
  AboutHistoryRoute: typeof AboutHistoryRoute
  InsightsPublicationsRoute: typeof InsightsPublicationsRoute
  InsightsTalksRoute: typeof InsightsTalksRoute
  PeopleSlugRoute: typeof PeopleSlugRoute
  PracticeAreasSlugRoute: typeof PracticeAreasSlugRoute
  AboutIndexRoute: typeof AboutIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  PracticeAreasIndexRoute: typeof PracticeAreasIndexRoute
  InsightsNewsSlugRoute: typeof InsightsNewsSlugRoute
  InsightsNewsIndexRoute: typeof InsightsNewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shell': {
      id: '/shell'
      path: '/shell'
      fullPath: '/shell'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/community': {
      id: '/about/community'
      path: '/about/community'
      fullPath: '/about/community'
      preLoaderRoute: typeof AboutCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/facilities': {
      id: '/about/facilities'
      path: '/about/facilities'
      fullPath: '/about/facilities'
      preLoaderRoute: typeof AboutFacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/history': {
      id: '/about/history'
      path: '/about/history'
      fullPath: '/about/history'
      preLoaderRoute: typeof AboutHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/publications': {
      id: '/insights/publications'
      path: '/insights/publications'
      fullPath: '/insights/publications'
      preLoaderRoute: typeof InsightsPublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/talks': {
      id: '/insights/talks'
      path: '/insights/talks'
      fullPath: '/insights/talks'
      preLoaderRoute: typeof InsightsTalksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$slug': {
      id: '/people/$slug'
      path: '/people/$slug'
      fullPath: '/people/$slug'
      preLoaderRoute: typeof PeopleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-areas/': {
      id: '/practice-areas/'
      path: '/practice-areas'
      fullPath: '/practice-areas/'
      preLoaderRoute: typeof PracticeAreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-areas/$slug': {
      id: '/practice-areas/$slug'
      path: '/practice-areas/$slug'
      fullPath: '/practice-areas/$slug'
      preLoaderRoute: typeof PracticeAreasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/news/': {
      id: '/insights/news/'
      path: '/insights/news'
      fullPath: '/insights/news/'
      preLoaderRoute: typeof InsightsNewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/news/$slug': {
      id: '/insights/news/$slug'
      path: '/insights/news/$slug'
      fullPath: '/insights/news/$slug'
      preLoaderRoute: typeof InsightsNewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ShellRoute: ShellRoute,
  AboutCommunityRoute: AboutCommunityRoute,
  AboutFacilitiesRoute: AboutFacilitiesRoute,
  AboutHistoryRoute: AboutHistoryRoute,
  InsightsPublicationsRoute: InsightsPublicationsRoute,
  InsightsTalksRoute: InsightsTalksRoute,
  PeopleSlugRoute: PeopleSlugRoute,
  PracticeAreasSlugRoute: PracticeAreasSlugRoute,
  AboutIndexRoute: AboutIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  PracticeAreasIndexRoute: PracticeAreasIndexRoute,
  InsightsNewsSlugRoute: InsightsNewsSlugRoute,
  InsightsNewsIndexRoute: InsightsNewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
